import '../fixtures/account/utils/account.commands'
import '../fixtures/quest/utils/quest.commands'
import '../fixtures/tracking/utils/tracking.commands'
import '../fixtures/missions/utils/missions.commands'
import '../fixtures/ui/ui.commands'